# Banco de dados
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dev_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 10000       # 10s
      validation-timeout: 5000        # 5s
      max-lifetime: 1800000           # 30min
      leak-detection-threshold: 60000 # 1min
  sql:
    init.platform: ${DB_PLATAFORM:postgres}
    init.mode: ${SQL_INITIALIZATION:always}
  #jpa
  jpa:
    generate-ddl: ${GENERATION_DDL:true}
    show-sql: ${SHOW_SQL:true}
    hibernate:
        ddl-auto: ${DDL_MODE:update}
        generate_statistics: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 15
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
          connection:
            provider_disables_autocommit: true
          query:
            in_clause_parameter_padding: true
            fail_on_pagination_over_collection_fetch: true
            plan_cache_max_size: 4096

##
# Book Client config
##
api:
  book:
    url: ${BOOK_URL:localhost:9090/api/books}

